#!/usr/bin/env bash

# Office-31
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 2 --dset office --output_dir log/SCDA/office31 --s_dset_path data/list/office31/amazon_31.txt --t_dset_path data/list/office31/webcam_31.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 2 --dset office --output_dir log/SCDA/office31 --s_dset_path data/list/office31/amazon_31.txt --t_dset_path data/list/office31/dslr_31.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.003
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 2 --dset office --output_dir log/SCDA/office31 --s_dset_path data/list/office31/webcam_31.txt --t_dset_path data/list/office31/amazon_31.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0  --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 2 --dset office --output_dir log/SCDA/office31 --s_dset_path data/list/office31/dslr_31.txt --t_dset_path data/list/office31/amazon_31.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 2 --dset office --output_dir log/SCDA/office31 --s_dset_path data/list/office31/dslr_31.txt --t_dset_path data/list/office31/webcam_31.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 2 --dset office --output_dir log/SCDA/office31 --s_dset_path data/list/office31/webcam_31.txt --t_dset_path data/list/office31/dslr_31.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01


# Office-Home
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Art_65.txt --t_dset_path data/list/OfficeHome/Clipart_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Art_65.txt --t_dset_path data/list/OfficeHome/Product_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Art_65.txt --t_dset_path data/list/OfficeHome/RealWorld_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0  --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Clipart_65.txt --t_dset_path data/list/OfficeHome/Art_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Clipart_65.txt --t_dset_path data/list/OfficeHome/Product_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Clipart_65.txt --t_dset_path data/list/OfficeHome/RealWorld_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Product_65.txt --t_dset_path data/list/OfficeHome/Art_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Product_65.txt --t_dset_path data/list/OfficeHome/Clipart_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/Product_65.txt --t_dset_path data/list/OfficeHome/RealWorld_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/RealWorld_65.txt --t_dset_path data/list/OfficeHome/Art_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/RealWorld_65.txt --t_dset_path data/list/OfficeHome/Clipart_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet50 --seed 1 --dset office-home --output_dir log/SCDA/home --s_dset_path data/list/OfficeHome/RealWorld_65.txt --t_dset_path data/list/OfficeHome/Product_65.txt --epochs 40 --iters-per-epoch 500 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01


# domainnet
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/clipart_train.txt --t_dset_path data/list/DomainNet/infograph_train.txt --t_test_path data/list/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/clipart_train.txt --t_dset_path data/list/DomainNet/painting_train.txt --t_test_path data/list/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/clipart_train.txt --t_dset_path data/list/DomainNet/quickdraw_train.txt --t_test_path data/list/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/clipart_train.txt --t_dset_path data/list/DomainNet/real_train.txt --t_test_path data/list/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/clipart_train.txt --t_dset_path data/list/DomainNet/sketch_train.txt --t_test_path data/list/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01

python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/infograph_train.txt --t_dset_path data/list/DomainNet/clipart_train.txt --t_test_path data/list/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/infograph_train.txt --t_dset_path data/list/DomainNet/painting_train.txt --t_test_path data/list/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/infograph_train.txt --t_dset_path data/list/DomainNet/quickdraw_train.txt --t_test_path data/list/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/infograph_train.txt --t_dset_path data/list/DomainNet/real_train.txt --t_test_path data/list/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/infograph_train.txt --t_dset_path data/list/DomainNet/sketch_train.txt --t_test_path data/list/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01

python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/painting_train.txt --t_dset_path data/list/DomainNet/clipart_train.txt --t_test_path data/list/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/painting_train.txt --t_dset_path data/list/DomainNet/infograph_train.txt --t_test_path data/list/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/painting_train.txt --t_dset_path data/list/DomainNet/quickdraw_train.txt --t_test_path data/list/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/painting_train.txt --t_dset_path data/list/DomainNet/real_train.txt --t_test_path data/list/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/painting_train.txt --t_dset_path data/list/DomainNet/sketch_train.txt --t_test_path data/list/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01

python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/quickdraw_train.txt --t_dset_path data/list/DomainNet/clipart_train.txt --t_test_path data/list/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/quickdraw_train.txt --t_dset_path data/list/DomainNet/infograph_train.txt --t_test_path data/list/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/quickdraw_train.txt --t_dset_path data/list/DomainNet/painting_train.txt --t_test_path data/list/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/quickdraw_train.txt --t_dset_path data/list/DomainNet/real_train.txt --t_test_path data/list/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/quickdraw_train.txt --t_dset_path data/list/DomainNet/sketch_train.txt --t_test_path data/list/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01

python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/real_train.txt --t_dset_path data/list/DomainNet/clipart_train.txt --t_test_path data/list/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/real_train.txt --t_dset_path data/list/DomainNet/infograph_train.txt --t_test_path data/list/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/real_train.txt --t_dset_path data/list/DomainNet/painting_train.txt --t_test_path data/list/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/real_train.txt --t_dset_path data/list/DomainNet/quickdraw_train.txt --t_test_path data/list/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/real_train.txt --t_dset_path data/list/DomainNet/sketch_train.txt --t_test_path data/list/DomainNet/sketch_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01

python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/sketch_train.txt --t_dset_path data/list/DomainNet/clipart_train.txt --t_test_path data/list/DomainNet/clipart_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/sketch_train.txt --t_dset_path data/list/DomainNet/infograph_train.txt --t_test_path data/list/DomainNet/infograph_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/sketch_train.txt --t_dset_path data/list/DomainNet/painting_train.txt --t_test_path data/list/DomainNet/painting_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/sketch_train.txt --t_dset_path data/list/DomainNet/quickdraw_train.txt --t_test_path data/list/DomainNet/quickdraw_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
python3 train_SCDA.py --gpu_id 8 --arch resnet101 --center_crop --seed 0 --dset domainnet --output_dir log/SCDA/domainnet --s_dset_path data/list/DomainNet/sketch_train.txt --t_dset_path data/list/DomainNet/real_train.txt --t_test_path data/list/DomainNet/real_test.txt --epochs 30 --iters-per-epoch 1000 --pdd_tradeoff 1.0 --MI_tradeoff 0.1 --temp 10.0 --threshold 0.8 --lr 0.01
